//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almotkaml.MFMinistry.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Notifications {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Notifications() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Almotkaml.MFMinistry.Resources.Notifications", typeof(Notifications).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة سجل غياب لموظف.
        /// </summary>
        public static string Absence_Create {
            get {
                return ResourceManager.GetString("Absence_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف سجل غياب لموظف.
        /// </summary>
        public static string Absence_Delete {
            get {
                return ResourceManager.GetString("Absence_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل سجل غياب لموظف.
        /// </summary>
        public static string Absence_Edit {
            get {
                return ResourceManager.GetString("Absence_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة صفة وظيفية جديدة.
        /// </summary>
        public static string AdjectiveEmployee_Create {
            get {
                return ResourceManager.GetString("AdjectiveEmployee_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف صفة وظيفية.
        /// </summary>
        public static string AdjectiveEmployee_Delete {
            get {
                return ResourceManager.GetString("AdjectiveEmployee_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل صفة وظيفية.
        /// </summary>
        public static string AdjectiveEmployee_Edit {
            get {
                return ResourceManager.GetString("AdjectiveEmployee_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة نوع صفة وظيفية جديدة.
        /// </summary>
        public static string AdjectiveEmployeeType_Create {
            get {
                return ResourceManager.GetString("AdjectiveEmployeeType_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف نوع صفة وظيفية.
        /// </summary>
        public static string AdjectiveEmployeeType_Delete {
            get {
                return ResourceManager.GetString("AdjectiveEmployeeType_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل نوع صفة وظيفية.
        /// </summary>
        public static string AdjectiveEmployeeType_Edit {
            get {
                return ResourceManager.GetString("AdjectiveEmployeeType_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة سجل سلف لموظف.
        /// </summary>
        public static string AdvancePayment_Create {
            get {
                return ResourceManager.GetString("AdvancePayment_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف سجل سلفة لموظف.
        /// </summary>
        public static string AdvancePayment_Delete {
            get {
                return ResourceManager.GetString("AdvancePayment_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل سجل سلفة لموظف.
        /// </summary>
        public static string AdvancePayment_Edit {
            get {
                return ResourceManager.GetString("AdvancePayment_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة عنصر إلى قائمة المصارف.
        /// </summary>
        public static string Bank_Create {
            get {
                return ResourceManager.GetString("Bank_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف عنصر من قائمة المصارف.
        /// </summary>
        public static string Bank_Delete {
            get {
                return ResourceManager.GetString("Bank_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل عنصر في قائمة المصارف.
        /// </summary>
        public static string Bank_Edit {
            get {
                return ResourceManager.GetString("Bank_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة عنصر إلى قائمة فروع المصارف.
        /// </summary>
        public static string BankBranch_Create {
            get {
                return ResourceManager.GetString("BankBranch_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف عنصر من قائمة فروع المصارف.
        /// </summary>
        public static string BankBranch_Delete {
            get {
                return ResourceManager.GetString("BankBranch_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل عنصر في قائمة فروع المصارف.
        /// </summary>
        public static string BankBranch_Edit {
            get {
                return ResourceManager.GetString("BankBranch_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة علاوة سنوية لموظف.
        /// </summary>
        public static string Bouns_Add {
            get {
                return ResourceManager.GetString("Bouns_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة فرع بلدي جديد.
        /// </summary>
        public static string Branch_Create {
            get {
                return ResourceManager.GetString("Branch_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف فرع بلدي.
        /// </summary>
        public static string Branch_Delete {
            get {
                return ResourceManager.GetString("Branch_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل فرع بلدي.
        /// </summary>
        public static string Branch_Edit {
            get {
                return ResourceManager.GetString("Branch_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة وحدة تنظيمية.
        /// </summary>
        public static string Center_Create {
            get {
                return ResourceManager.GetString("Center_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف وحدة تنظيمية.
        /// </summary>
        public static string Center_Delete {
            get {
                return ResourceManager.GetString("Center_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل وحدة تنظيمية.
        /// </summary>
        public static string Center_Edit {
            get {
                return ResourceManager.GetString("Center_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة عنصر في قائمة المدن.
        /// </summary>
        public static string City_Create {
            get {
                return ResourceManager.GetString("City_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف عنصر في قائمة المدن.
        /// </summary>
        public static string City_Delete {
            get {
                return ResourceManager.GetString("City_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل عنصر في قائمة المدن.
        /// </summary>
        public static string City_Edit {
            get {
                return ResourceManager.GetString("City_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتحديث بيانات الشركة.
        /// </summary>
        public static string CompanyInfo_Update {
            get {
                return ResourceManager.GetString("CompanyInfo_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة نوع تعاقد.
        /// </summary>
        public static string ContractType_Create {
            get {
                return ResourceManager.GetString("ContractType_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف نوع تعاقد.
        /// </summary>
        public static string ContractType_Delete {
            get {
                return ResourceManager.GetString("ContractType_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل نوع تعاقد.
        /// </summary>
        public static string ContractType_Edit {
            get {
                return ResourceManager.GetString("ContractType_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة عنصر في قائمة البلدان.
        /// </summary>
        public static string Country_Create {
            get {
                return ResourceManager.GetString("Country_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف عنصر في قائمة البلدان.
        /// </summary>
        public static string Country_Delete {
            get {
                return ResourceManager.GetString("Country_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل عنصر في قائمة البلدان.
        /// </summary>
        public static string Country_Edit {
            get {
                return ResourceManager.GetString("Country_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة درجة لموظف.
        /// </summary>
        public static string Degree_Add {
            get {
                return ResourceManager.GetString("Degree_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة درجة لموظف.
        /// </summary>
        public static string Degree_Edit {
            get {
                return ResourceManager.GetString("Degree_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتسجيل موظف كمنتدب / متفرغ إلى الجهة.
        /// </summary>
        public static string Delegation_Create {
            get {
                return ResourceManager.GetString("Delegation_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف موظف منتدب / متفرغ إلى الجهة.
        /// </summary>
        public static string Delegation_Delete {
            get {
                return ResourceManager.GetString("Delegation_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل موظف منتدب / متفرغ إلى الجهة.
        /// </summary>
        public static string Delegation_Edit {
            get {
                return ResourceManager.GetString("Delegation_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة إدارة.
        /// </summary>
        public static string Department_Create {
            get {
                return ResourceManager.GetString("Department_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف إدارة.
        /// </summary>
        public static string Department_Delete {
            get {
                return ResourceManager.GetString("Department_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل إدارة.
        /// </summary>
        public static string Department_Edit {
            get {
                return ResourceManager.GetString("Department_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة قسم جديد.
        /// </summary>
        public static string Division_Create {
            get {
                return ResourceManager.GetString("Division_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف قسم.
        /// </summary>
        public static string Division_Delete {
            get {
                return ResourceManager.GetString("Division_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل قسم.
        /// </summary>
        public static string Division_Edit {
            get {
                return ResourceManager.GetString("Division_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة وثيقة (ملف) موظف جديد.
        /// </summary>
        public static string Document_Create {
            get {
                return ResourceManager.GetString("Document_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف وثيقة (ملف) موظف.
        /// </summary>
        public static string Document_Delete {
            get {
                return ResourceManager.GetString("Document_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل وثيقة (ملف) موظف.
        /// </summary>
        public static string Document_Edit {
            get {
                return ResourceManager.GetString("Document_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة عنصر جديد في قائمة أنواع الوثائق.
        /// </summary>
        public static string DocumentType_Create {
            get {
                return ResourceManager.GetString("DocumentType_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة عنصر في قائمة أنواع الوثائق.
        /// </summary>
        public static string DocumentType_Delete {
            get {
                return ResourceManager.GetString("DocumentType_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل عنصر في قائمة أنواع الوثائق.
        /// </summary>
        public static string DocumentType_Edit {
            get {
                return ResourceManager.GetString("DocumentType_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة درج جديد.
        /// </summary>
        public static string Drawer_Create {
            get {
                return ResourceManager.GetString("Drawer_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف عنصر في قائمة الأدراج.
        /// </summary>
        public static string Drawer_Delete {
            get {
                return ResourceManager.GetString("Drawer_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل عنصر في قائمة الأدراج.
        /// </summary>
        public static string Drawer_Edit {
            get {
                return ResourceManager.GetString("Drawer_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بالترقية.
        /// </summary>
        public static string Employee_Promotion {
            get {
                return ResourceManager.GetString("Employee_Promotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بالتسوية.
        /// </summary>
        public static string Employee_Settlement {
            get {
                return ResourceManager.GetString("Employee_Settlement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بعمل إهناء خدمة لموظف.
        /// </summary>
        public static string EndServices_Create {
            get {
                return ResourceManager.GetString("EndServices_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف سجل موظف من قائمة إنهاء الخدمات.
        /// </summary>
        public static string EndServices_Delete {
            get {
                return ResourceManager.GetString("EndServices_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل سجل إنهاء خدمة لموظف.
        /// </summary>
        public static string EndServices_Edit {
            get {
                return ResourceManager.GetString("EndServices_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة سجل تقييم لموظف.
        /// </summary>
        public static string Evaluation_Create {
            get {
                return ResourceManager.GetString("Evaluation_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف سجل تقييم لموظف.
        /// </summary>
        public static string Evaluation_Delete {
            get {
                return ResourceManager.GetString("Evaluation_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل سجل تقييم لموظف.
        /// </summary>
        public static string Evaluation_Edit {
            get {
                return ResourceManager.GetString("Evaluation_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة عنصر في قائمة التخصصات الدقيقة.
        /// </summary>
        public static string ExactSpecialty_Create {
            get {
                return ResourceManager.GetString("ExactSpecialty_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف عنصر في قائمة التخصصات الدقيقة.
        /// </summary>
        public static string ExactSpecialty_Delete {
            get {
                return ResourceManager.GetString("ExactSpecialty_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل عنصر في قائمة التخصصات الدقيقة.
        /// </summary>
        public static string ExactSpecialty_Edit {
            get {
                return ResourceManager.GetString("ExactSpecialty_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتسجيل عمل إضافي لموظف.
        /// </summary>
        public static string Extrawork_Create {
            get {
                return ResourceManager.GetString("Extrawork_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف سجل عمل إضافي لموظف.
        /// </summary>
        public static string Extrawork_Delete {
            get {
                return ResourceManager.GetString("Extrawork_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل سجل عمل إضافي لموظف.
        /// </summary>
        public static string Extrawork_Edit {
            get {
                return ResourceManager.GetString("Extrawork_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة مجموعة مالية.
        /// </summary>
        public static string FinancialGroup_Create {
            get {
                return ResourceManager.GetString("FinancialGroup_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف مجموعة مالية.
        /// </summary>
        public static string FinancialGroup_Delete {
            get {
                return ResourceManager.GetString("FinancialGroup_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل  بيانات مجموعة مالية.
        /// </summary>
        public static string FinancialGroup_Edit {
            get {
                return ResourceManager.GetString("FinancialGroup_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة سجل في قائمة العطل الرسمية.
        /// </summary>
        public static string Holiday_Create {
            get {
                return ResourceManager.GetString("Holiday_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف سجل في قائمة العطل الرسمية.
        /// </summary>
        public static string Holiday_Delete {
            get {
                return ResourceManager.GetString("Holiday_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل سجل في قائمة العطل الرسمية.
        /// </summary>
        public static string Holiday_Edit {
            get {
                return ResourceManager.GetString("Holiday_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة عنصر إلى قائمة الوظائف.
        /// </summary>
        public static string Job_Create {
            get {
                return ResourceManager.GetString("Job_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف عنصر من قائمة الوظائف.
        /// </summary>
        public static string Job_Delete {
            get {
                return ResourceManager.GetString("Job_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل عنصر في قائمة الوظائف.
        /// </summary>
        public static string Job_Edit {
            get {
                return ResourceManager.GetString("Job_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة مذكرة بيانات شهيد.
        /// </summary>
        public static string MartyrForm_Create {
            get {
                return ResourceManager.GetString("MartyrForm_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف مذكرة بيانات شهيد.
        /// </summary>
        public static string MartyrForm_Delete {
            get {
                return ResourceManager.GetString("MartyrForm_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل مذكرة بيانات شهيد.
        /// </summary>
        public static string MartyrForm_Edit {
            get {
                return ResourceManager.GetString("MartyrForm_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة عنصر إلى قائمة الجنسيات.
        /// </summary>
        public static string Nationality_Create {
            get {
                return ResourceManager.GetString("Nationality_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف عنصر من قائمة الجنسيات.
        /// </summary>
        public static string Nationality_Delete {
            get {
                return ResourceManager.GetString("Nationality_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل عنصر في قائمة الجنسيات.
        /// </summary>
        public static string Nationality_Edit {
            get {
                return ResourceManager.GetString("Nationality_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة محلة.
        /// </summary>
        public static string Place_Create {
            get {
                return ResourceManager.GetString("Place_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف محلة.
        /// </summary>
        public static string Place_Delete {
            get {
                return ResourceManager.GetString("Place_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل محلة.
        /// </summary>
        public static string Place_Edit {
            get {
                return ResourceManager.GetString("Place_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة حقل علاوة أو خصم في بيانات الموظفين المالية.
        /// </summary>
        public static string Premium_Create {
            get {
                return ResourceManager.GetString("Premium_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف حقل علاوة أو خصم في بيانات الموظفين المالية.
        /// </summary>
        public static string Premium_Delete {
            get {
                return ResourceManager.GetString("Premium_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل حقل علاوة أو خصم في بيانات الموظفين المالية.
        /// </summary>
        public static string Premium_Edit {
            get {
                return ResourceManager.GetString("Premium_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة مؤهل علمي.
        /// </summary>
        public static string Qualification_Create {
            get {
                return ResourceManager.GetString("Qualification_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف مؤهل علمي.
        /// </summary>
        public static string Qualification_Delete {
            get {
                return ResourceManager.GetString("Qualification_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل مؤهل علمي.
        /// </summary>
        public static string Qualification_Edit {
            get {
                return ResourceManager.GetString("Qualification_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة نوع مؤهل علمي.
        /// </summary>
        public static string QualificationType_Create {
            get {
                return ResourceManager.GetString("QualificationType_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف نوع مؤهل علمي.
        /// </summary>
        public static string QualificationType_Delete {
            get {
                return ResourceManager.GetString("QualificationType_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قائمة بتعديل نوع مؤهل علمي.
        /// </summary>
        public static string QualificationType_Edit {
            get {
                return ResourceManager.GetString("QualificationType_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة فئة مستفيدة .
        /// </summary>
        public static string RecipientGroup_Create {
            get {
                return ResourceManager.GetString("RecipientGroup_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف فئة مستفيدة.
        /// </summary>
        public static string RecipientGroup_Delete {
            get {
                return ResourceManager.GetString("RecipientGroup_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل بيانات فئة مستفيدة.
        /// </summary>
        public static string RecipientGroup_Edit {
            get {
                return ResourceManager.GetString("RecipientGroup_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بمنح مكافأة لموظف.
        /// </summary>
        public static string Reward_Create {
            get {
                return ResourceManager.GetString("Reward_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف مكافأة لموظف.
        /// </summary>
        public static string Reward_Delete {
            get {
                return ResourceManager.GetString("Reward_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل مكافأة لموظف.
        /// </summary>
        public static string Reward_Edit {
            get {
                return ResourceManager.GetString("Reward_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة عنصر إلى قائمة أنواع المكافآت.
        /// </summary>
        public static string RewardType_Create {
            get {
                return ResourceManager.GetString("RewardType_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف عنصر في قائمة أنواع المكافآت.
        /// </summary>
        public static string RewardType_Delete {
            get {
                return ResourceManager.GetString("RewardType_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل عنصر في قائمة أنواع المكافآت.
        /// </summary>
        public static string RewardType_Edit {
            get {
                return ResourceManager.GetString("RewardType_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بخصم السلف للموظفين.
        /// </summary>
        public static string Salary_Allow {
            get {
                return ResourceManager.GetString("Salary_Allow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإغلاق مرتبات الشهر للموظفين.
        /// </summary>
        public static string Salary_Close {
            get {
                return ResourceManager.GetString("Salary_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Salary_Delete {
            get {
                return ResourceManager.GetString("Salary_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل بيانات المرتب لموظف.
        /// </summary>
        public static string Salary_Edit {
            get {
                return ResourceManager.GetString("Salary_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتجميد سلف الموظفين.
        /// </summary>
        public static string Salary_Freeze {
            get {
                return ResourceManager.GetString("Salary_Freeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Salary_OldSalary {
            get {
                return ResourceManager.GetString("Salary_OldSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Salary_Spent {
            get {
                return ResourceManager.GetString("Salary_Spent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإيقاف مرتب.
        /// </summary>
        public static string Salary_Suspend {
            get {
                return ResourceManager.GetString("Salary_Suspend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإفراج مرتب.
        /// </summary>
        public static string Salary_Unsuspend {
            get {
                return ResourceManager.GetString("Salary_Unsuspend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام باحتساب مرتبات الموظفين.
        /// </summary>
        public static string Salary_Update {
            get {
                return ResourceManager.GetString("Salary_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتحديث البيانات المالية لموظف.
        /// </summary>
        public static string SalaryInfo_Save {
            get {
                return ResourceManager.GetString("SalaryInfo_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة عقوبة لموظف.
        /// </summary>
        public static string Sanction_Create {
            get {
                return ResourceManager.GetString("Sanction_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف عقوبة لموظف.
        /// </summary>
        public static string Sanction_Delete {
            get {
                return ResourceManager.GetString("Sanction_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل عقوبة لموظف.
        /// </summary>
        public static string Sanction_Edit {
            get {
                return ResourceManager.GetString("Sanction_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة عنصر في قائمة أنواع العقوبات.
        /// </summary>
        public static string SanctionType_Create {
            get {
                return ResourceManager.GetString("SanctionType_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف عنصر في قائمة أنواع العقوبات.
        /// </summary>
        public static string SanctionType_Delete {
            get {
                return ResourceManager.GetString("SanctionType_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل عنصر في قائمة أنواع العقوبات.
        /// </summary>
        public static string SanctionType_Edit {
            get {
                return ResourceManager.GetString("SanctionType_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة دورة ذاتية.
        /// </summary>
        public static string SelfCourse_Create {
            get {
                return ResourceManager.GetString("SelfCourse_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف دورة ذاتية.
        /// </summary>
        public static string SelfCourse_Delete {
            get {
                return ResourceManager.GetString("SelfCourse_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل دورة ذاتية.
        /// </summary>
        public static string SelfCourse_Edit {
            get {
                return ResourceManager.GetString("SelfCourse_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتحديث إعدادات المنظومة.
        /// </summary>
        public static string Setting_Update {
            get {
                return ResourceManager.GetString("Setting_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة سجل في تسوية الوضع.
        /// </summary>
        public static string SituationResolveJob_Create {
            get {
                return ResourceManager.GetString("SituationResolveJob_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف سجل في تسوية الوضع.
        /// </summary>
        public static string SituationResolveJob_Delete {
            get {
                return ResourceManager.GetString("SituationResolveJob_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل سجل في تسوية الوضع.
        /// </summary>
        public static string SituationResolveJob_Edit {
            get {
                return ResourceManager.GetString("SituationResolveJob_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة عنصر في قائمة التخصصات.
        /// </summary>
        public static string Specialty_Create {
            get {
                return ResourceManager.GetString("Specialty_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف عنصر من قائمة التخصصات.
        /// </summary>
        public static string Specialty_Delete {
            get {
                return ResourceManager.GetString("Specialty_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل عنصر في قائمة التخصصات.
        /// </summary>
        public static string Specialty_Edit {
            get {
                return ResourceManager.GetString("Specialty_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة عنصر في قائمة الملاك الوظيفي.
        /// </summary>
        public static string Staffing_Create {
            get {
                return ResourceManager.GetString("Staffing_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف عنصر من قائمة الملاك الوظيفي.
        /// </summary>
        public static string Staffing_Delete {
            get {
                return ResourceManager.GetString("Staffing_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل عنصر في قائمة الملاك الوظيفي.
        /// </summary>
        public static string Staffing_Edit {
            get {
                return ResourceManager.GetString("Staffing_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة عنصر في قائمة نوع الملاك الوظيفي.
        /// </summary>
        public static string StaffingType_Create {
            get {
                return ResourceManager.GetString("StaffingType_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف عنصر من قائمة نوع الملاك الوظيفي.
        /// </summary>
        public static string StaffingType_Delete {
            get {
                return ResourceManager.GetString("StaffingType_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل عنصر في قائمة نوع الملاك الوظيفي.
        /// </summary>
        public static string StaffingType_Edit {
            get {
                return ResourceManager.GetString("StaffingType_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة عنصر في قائمة التخصصات الفرعية.
        /// </summary>
        public static string SubSpecialty_Create {
            get {
                return ResourceManager.GetString("SubSpecialty_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف عنصر من قائمة التخصصات الفرعية.
        /// </summary>
        public static string SubSpecialty_Delete {
            get {
                return ResourceManager.GetString("SubSpecialty_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل عنصر في قائمة التخصصات الفرعية.
        /// </summary>
        public static string SubSpecialty_Edit {
            get {
                return ResourceManager.GetString("SubSpecialty_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بافراج مرتب موظف.
        /// </summary>
        public static string Suspsended {
            get {
                return ResourceManager.GetString("Suspsended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة تدريب.
        /// </summary>
        public static string Training_Create {
            get {
                return ResourceManager.GetString("Training_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف تدريب.
        /// </summary>
        public static string Training_Delete {
            get {
                return ResourceManager.GetString("Training_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل تدريب.
        /// </summary>
        public static string Training_Edit {
            get {
                return ResourceManager.GetString("Training_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة مركز تدريب.
        /// </summary>
        public static string TrainingCenter_Create {
            get {
                return ResourceManager.GetString("TrainingCenter_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف مركز تدريب.
        /// </summary>
        public static string TrainingCenter_Delete {
            get {
                return ResourceManager.GetString("TrainingCenter_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل مركز تدريب.
        /// </summary>
        public static string TrainingCenter_Edit {
            get {
                return ResourceManager.GetString("TrainingCenter_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتسجيل موظف كمنتدب / متفرغ خارج الجهة.
        /// </summary>
        public static string Transfer_Create {
            get {
                return ResourceManager.GetString("Transfer_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف موظف منتدب / متفرغ خارج الجهة.
        /// </summary>
        public static string Transfer_Delete {
            get {
                return ResourceManager.GetString("Transfer_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل موظف منتدب / متفرغ خارج الجهة.
        /// </summary>
        public static string Transfer_Edit {
            get {
                return ResourceManager.GetString("Transfer_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة وحدة جديدة.
        /// </summary>
        public static string Unit_Create {
            get {
                return ResourceManager.GetString("Unit_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف وحدة.
        /// </summary>
        public static string Unit_Delete {
            get {
                return ResourceManager.GetString("Unit_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل وحدة.
        /// </summary>
        public static string Unit_Edit {
            get {
                return ResourceManager.GetString("Unit_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة مستخدم جديد.
        /// </summary>
        public static string User_Create {
            get {
                return ResourceManager.GetString("User_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف مستخدم.
        /// </summary>
        public static string User_Delete {
            get {
                return ResourceManager.GetString("User_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل مستخدم.
        /// </summary>
        public static string User_Edit {
            get {
                return ResourceManager.GetString("User_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة مجموعة صلاحيات جديدة.
        /// </summary>
        public static string UserGroup_Create {
            get {
                return ResourceManager.GetString("UserGroup_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف مجموعة صلاحيات مستخدمين.
        /// </summary>
        public static string UserGroup_Delete {
            get {
                return ResourceManager.GetString("UserGroup_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل صلاحيات مستخدمين.
        /// </summary>
        public static string UserGroup_Edit {
            get {
                return ResourceManager.GetString("UserGroup_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بمنح إجازة لموظف.
        /// </summary>
        public static string Vacation_Create {
            get {
                return ResourceManager.GetString("Vacation_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف إجازة لموظف.
        /// </summary>
        public static string Vacation_Delete {
            get {
                return ResourceManager.GetString("Vacation_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل إجازة موظف.
        /// </summary>
        public static string Vacation_Edit {
            get {
                return ResourceManager.GetString("Vacation_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة عنصر في قائمة الإجازات.
        /// </summary>
        public static string VacationType_Create {
            get {
                return ResourceManager.GetString("VacationType_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف عنصر في قائمة الإجازات.
        /// </summary>
        public static string VacationType_Delete {
            get {
                return ResourceManager.GetString("VacationType_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل عنصر في قائمة الإجازات.
        /// </summary>
        public static string VacationType_Edit {
            get {
                return ResourceManager.GetString("VacationType_Edit", resourceCulture);
            }
        }
    }
}
